#!/bin/sh

BASEDIR=$(dirname $0)
# echo $BASEDIR/

# delete the current translation
rm $BASEDIR/*.pot

# move unwanted folders
mv $BASEDIR/../bower_components/ $BASEDIR/../../.
# mv $BASEDIR/../woocommerce/ $BASEDIR/../../.

# execute
php $BASEDIR/../_misc/translate/makepot.php wp-theme $BASEDIR/../.

# move .pot file to right dir
mv *.pot $BASEDIR/

# move back folders
mv $BASEDIR/../../bower_components/ $BASEDIR/../.
# mv $BASEDIR/../../woocommerce/ $BASEDIR/../.

exit 0