var html = '<style type="text/css">';
	html += ' .wrap-h-banner{ ';
	html += ' border-radius: 4px; ';
	html += ' box-shadow: 0 0 1px #000000; ';
	html += ' display: inline-block; ';
	html += ' padding: 0 15px; ';
	html += ' position: relative; ';
	html += ' background: url(http://rdbuploads.s3.amazonaws.com/backgrounds/bg-handyman1.png) no-repeat scroll rgba(0,0,0,0.5); ';
	html += ' background-size: cover; ';
	html += ' background-position: center center; ';
	html += ' height: 80px; ';
	html += ' width: 728px; ';
	html += ' font-family: sans-serif;';
	html += ' } ';
	html += ' h1.h1-script{ ';
	html += ' font-family: inherit; ';
	html += ' font-weight: 500; ';
	html += ' line-height: 1.1; ';
	html += ' color: #fff; ';
	html += ' margin-top: 0; ';
	html += ' margin-bottom: 0; ';
	html += ' font-size: 36px; ';
	html += ' text-align: center; ';
	html += ' text-shadow: 2px 2px #666666; ';
	html += ' } ';
	html += ' .form-control { ';
	html += ' display: block; ';
	html += ' width: 100%; ';
	html += ' height: 34px; ';
	html += ' padding: 6px 12px; ';
	html += ' font-size: 14px; ';
	html += ' line-height: 1.42857143; ';
	html += ' color: #555; ';
	html += ' background-color: #fff; ';
	html += ' background-image: none; ';
	html += ' border: 1px solid #ccc; ';
	html += ' border-radius: 4px; ';
	html += ' -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075); ';
	html += ' box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075); ';
	html += ' -webkit-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s; ';
	html += ' transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s; ';
	html += ' } ';
	html += ' .form-control:focus { ';
	html += ' border-color: #66afe9; ';
	html += ' outline: 0; ';
	html += ' -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6); ';
	html += ' box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6); ';
	html += ' } ';
	html += ' .form-control::-moz-placeholder { ';
	html += ' color: #999; ';
	html += ' opacity: 1; ';
	html += ' } ';
	html += ' .form-control:-ms-input-placeholder { ';
	html += ' color: #999; ';
	html += ' } ';
	html += ' .form-control::-webkit-input-placeholder { ';
	html += ' color: #999; ';
	html += ' } ';
	html += ' .form-group { ';
	html += ' margin-bottom: 15px; ';
	html += ' } ';
	html += ' .input-lg { ';
	html += ' height: 46px; ';
	html += ' padding: 10px 16px; ';
	html += ' font-size: 18px; ';
	html += ' line-height: 1.33; ';
	html += ' border-radius: 6px; ';
	html += ' } ';
	html += ' select.input-lg { ';
	html += ' height: 46px; ';
	html += ' line-height: 46px; ';
	html += ' } ';
	html += ' .form-inline { ';
	html += ' text-align: center;';
	html += ' } ';
	html += ' .form-inline .form-group { ';
	html += ' display: inline-block; ';
	html += ' margin-bottom: 0; ';
	html += ' vertical-align: middle; ';
	html += ' } ';
	html += ' .form-inline .form-control { ';
	html += ' display: inline-block; ';
	html += ' width: auto; ';
	html += ' vertical-align: middle; ';
	html += ' } ';
	html += ' .btn { ';
	html += ' display: inline-block; ';
	html += ' padding: 6px 12px; ';
	html += ' margin-bottom: 0; ';
	html += ' font-size: 14px; ';
	html += ' font-weight: normal; ';
	html += ' line-height: 1.42857143; ';
	html += ' text-align: center; ';
	html += ' white-space: nowrap; ';
	html += ' vertical-align: middle; ';
	html += ' cursor: pointer; ';
	html += ' -webkit-user-select: none; ';
	html += ' -moz-user-select: none; ';
	html += ' -ms-user-select: none; ';
	html += ' user-select: none; ';
	html += ' background-image: none; ';
	html += ' border: 1px solid transparent; ';
	html += ' border-radius: 4px; ';
	html += ' } ';
	html += ' .btn:focus, ';
	html += ' .btn:active:focus, ';
	html += ' .btn.active:focus { ';
	html += ' outline: thin dotted; ';
	html += ' outline: 5px auto -webkit-focus-ring-color; ';
	html += ' outline-offset: -2px; ';
	html += ' } ';
	html += ' .btn:hover, ';
	html += ' .btn:focus { ';
	html += ' color: #333; ';
	html += ' text-decoration: none; ';
	html += ' } ';
	html += ' .btn-danger { ';
	html += ' color: #fff; ';
	html += ' background-color: #d9534f; ';
	html += ' border-color: #d43f3a; ';
	html += ' } ';
	html += ' .btn-danger:hover, ';
	html += ' .btn-danger:focus, ';
	html += ' .btn-danger:active, ';
	html += ' .btn-danger.active, ';
	html += ' .open .dropdown-toggle.btn-danger { ';
	html += ' color: #fff; ';
	html += ' background-color: #d2322d; ';
	html += ' border-color: #ac2925; ';
	html += ' } ';
	html += ' .btn-danger:active, ';
	html += ' .btn-danger.active, ';
	html += ' .open .dropdown-toggle.btn-danger { ';
	html += ' background-image: none; ';
	html += ' } ';
	html += ' .btn-lg{ ';
	html += ' padding: 10px 16px; ';
	html += ' font-size: 18px; ';
	html += ' line-height: 1.33; ';
	html += ' border-radius: 6px; ';
	html += ' } ';
	html += ' .sr-only { ';
	html += ' position: absolute; ';
	html += ' width: 1px; ';
	html += ' height: 1px; ';
	html += ' padding: 0; ';
	html += ' margin: -1px; ';
	html += ' overflow: hidden; ';
	html += ' clip: rect(0, 0, 0, 0); ';
	html += ' border: 0; ';
	html += ' } ';
	html += ' </style>';
	html += ' <div class="wrap-h-banner"> ';
	html += ' <h1 class="h1-script">Find your hometown handyman today!</h1> ';
	html += ' <form action="<?echo $aff_id?>" class="form-inline"> ';
	html += ' <div class="form-group"> ';
	html += ' <label class="sr-only">Choose Type Project</label> ';
	html += ' <select class="form-control"> ';
	html += ' <option value="">Choose Type of Project</option> ';
	html += ' <option value="1">Air Conditioning</option> ';
	html += ' <option value="2">Appliance Installation and Repair</option> ';
	html += ' <option value="3">Architect</option> ';
	html += ' <option value="4">Attics and Basements</option> ';
	html += ' <option value="54">Basements</option> ';
	html += ' <option value="5">Bathroom Remodeling</option> ';
	html += ' <option value="6">Cabinets</option> ';
	html += ' <option value="7">Carpentry</option> ';
	html += ' <option value="8">Cleaning</option> ';
	html += ' <option value="9">Closets and Storage</option> ';
	html += ' <option value="10">Countertops</option> ';
	html += ' <option value="11">Custom Home Building</option> ';
	html += ' <option value="55">Customer Home Remodeling</option> ';
	html += ' <option value="12">Decks</option> ';
	html += ' <option value="13">Demolition and Disposal</option> ';
	html += ' <option value="14">Designer</option> ';
	html += ' <option value="15">Drywall and Plastering</option> ';
	html += ' <option value="16">Electrical</option> ';
	html += ' <option value="17">Environmental/Disaster Services</option> ';
	html += ' <option value="18">Excavation</option> ';
	html += ' <option value="19">Fans and Ventilation</option> ';
	html += ' <option value="20">Fencing</option> ';
	html += ' <option value="21">Financing</option> ';
	html += ' <option value="22">Fireplace</option> ';
	html += ' <option value="23">Floor Coverings</option> ';
	html += ' <option value="24">Foundations</option> ';
	html += ' <option value="25">Framing Systems</option> ';
	html += ' <option value="26">Garages/Outbuildings</option> ';
	html += ' <option value="31">Gate for Driveway or Security - Install or Re</option> ';
	html += ' <option value="27">Glass and Screens</option> ';
	html += ' <option value="28">Gutters</option> ';
	html += ' <option value="29">Handyman</option> ';
	html += ' <option value="30">Heating and Ventilation</option> ';
	html += ' <option value="56">Home Additions</option> ';
	html += ' <option value="32">Hot Tubs</option> ';
	html += ' <option value="33">Inspection and Appraisal</option> ';
	html += ' <option value="34">Insulation and Weather Stripping</option> ';
	html += ' <option value="35">Kitchen Remodeling</option> ';
	html += ' <option value="36">Landscaping</option> ';
	html += ' <option value="37">Marine</option> ';
	html += ' <option value="38">Masonry</option> ';
	html += ' <option value="39">Mold Remediation</option> ';
	html += ' <option value="40">Odd-Jobs</option> ';
	html += ' <option value="41">Other</option> ';
	html += ' <option value="42">Painting/Wallcovering</option> ';
	html += ' <option value="43">Paving</option> ';
	html += ' <option value="44">Pest Control</option> ';
	html += ' <option value="45">Plumbing</option> ';
	html += ' <option value="46">Pools</option> ';
	html += ' <option value="57">Railings</option> ';
	html += ' <option value="47">Remodeling/Additions</option> ';
	html += ' <option value="48">Roofing</option> ';
	html += ' <option value="49">Siding/Residing</option> ';
	html += ' <option value="58">Smart House</option> ';
	html += ' <option value="50">Sunrooms</option> ';
	html += ' <option value="51">Tile and Stone</option> ';
	html += ' <option value="52">Waterproofing</option> ';
	html += ' <option value="53">Windows</option> ';
	html += ' </select> ';
	html += ' </div> ';
	html += ' <div class="form-group"> ';
	html += ' <label class="sr-only">Zipcode</label> ';
	html += ' <input class="form-control" type="text" placeholder="Zipcode"> ';
	html += ' <input type="hidden" value="http://handyman.com" name="url"/> ';
	html += ' </div> ';
	html += ' <div class="form-group"> ';
	html += ' <button class="btn btn-danger">Go</button> ';
	html += ' </div> ';
	html += ' </form> ';
	html += ' </div> ';
	document.write(html);