<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/includes/buzz_functions.php' );
require ( get_template_directory() . '/includes/admin_menu.php' );
require ( get_template_directory() . '/includes/widgets/widget-tabs.php' );
?>